### ISSUE TITLE
server: return repays, refactor activity endpoint

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#133]

**Comment by nfmelendez** [comment]
batching http requests using viem:

https://viem.sh/docs/clients/transports/http.html#batch-json-rpc

**Comment by cruzdanilo** [comment]
@nfmelendez how are you measuring how many actual rpc calls were made?

**Comment by nfmelendez** [comment]
i am using the time as proxy, but actually i could see it with the script that actually logs de rpc call, my assumption is that the call of 1 block was 1 RPC that took 696ms, and asking x500 only is x2 so must be a single batch rpc. will check that the logs says

**Comment by nfmelendez** [comment]
**Example of a withdraw**

User operation

https://jiffyscan.xyz/userOpHash/0xdeea878373790afb3d905412fdc5a9d0ea4b18be9502b78171bbca640c1139ee?network=optimism&section=logs

Asset transfer

https://optimistic.etherscan.io/tx/0x8b6523cddece99a40e35c3724ea1cd5eca0eff0bcc542c097c1b64af25255689
