### ISSUE TITLE
ui: ask for permission to use the camera

### ISSUE THREAD

**Issue by Mateo-Soso** [exactly/mobile#176]
We need to ask for permission from the users to access their cameras. Apple pointed out this in their review
![Image](https://github.com/user-attachments/assets/19ea7c38-ea4c-4ec5-ae49-e8298e401a75)

**Comment by dieguezguille** [comment]
they seem to be asking us to add a brief explanation of the camera usage and update the copy on the permission button to something like "Continue" or "Next"
