### ISSUE TITLE
server: filter out empty block traces on sentry

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#178]

**Comment by nfmelendez** [comment]
Sentry HTTP request instrumentation: https://docs.sentry.io/platforms/javascript/guides/node/tracing/instrumentation/custom-instrumentation/requests-module/

**Comment by nfmelendez** [comment]
General information about integrations:
https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/#modifying-default-integrations

How to ignore ongoing requests
https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/http/

**Comment by nfmelendez** [comment]
Fixed: https://github.com/exactly/mobile/commit/c042da5a53280988ebfd4b57181cee2d13c8c097
