### ISSUE TITLE
persona: add new fields to template

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#227]

**Comment by Mateo-Soso** [comment]
New fields will only be filled by new users. Already approved inquiries can't go back to fill these new fields.

We will need to create a new template for these users. I suggest we trigger the new flow when the users click to update the plug-in. 

Here is the response by Persona regarding this
`No, once an inquiry has reached a terminal status (eg. approved, declined) there is no way to make further changes to it - except to approve a previously declined inquiry or decline a previously approved inquiry.`
