### ISSUE TITLE
Review Bridge documentation pre signing

### ISSUE THREAD

**Issue by Mateo-Soso** [exactly/mobile#234]
[API docs](https://apidocs.bridge.xyz/docs)

https://apidocs.bridge.xyz/reference/get_customers

**Comment by nfmelendez** [comment]
Approved.  integration is 80% backend and 20% front.  
We have to share KYC information but we already have a persona hook for that operation. 
Works in optimism
Apply rules for certain states of USA 

https://apidocs.bridge.xyz/docs/quick-start
https://apidocs.bridge.xyz/docs/on-ramp
https://apidocs.bridge.xyz/docs/blockchains
https://apidocs.bridge.xyz/docs/countries
