### ISSUE TITLE
integrate persona kyc

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#4]

**Comment by Mateo-Soso** [comment]
Lastly, as discussed I'd encourage you all to review our best practices documentation:
- [Inquiry best practices](https://docs.withpersona.com/docs/inquiries-best-practices) (reference IDs, Webhooks, pre-filling fields)
- [Prevent users from creating multiple inquiries](https://docs.withpersona.com/docs/prevent-users-from-creating-multiple-inquiries)
- [Expired Inquiries and how to handle them](https://docs.withpersona.com/docs/inquiries-resuming-inquiries#resuming-inquiries-vs-creating-new-inquiries)
