### ISSUE TITLE
landing: implement new design

### ISSUE THREAD

**Issue by FedeNZ** [exactly/mobile#44]
For the launch of the Exa App we will need a landing page to provide more information to the users about how it works and the benefits they will get by using it.

Main topics:
- Buy now, pay later.
- Hold your crypto.
- Credit + installments
- Coming soon:
   • Debit
   • Borrows
   • Fixed deposits
   • RWA

**Comment by Mateo-Soso** [comment]
[Exa App Landing research](https://docs.google.com/presentation/d/1T6uOxugLftCvLP27qQAFBDBvJmQkwQCQlHraOVkjgQ4/edit?usp=sharing)

**Comment by cruzdanilo** [comment]
mobile
