### ISSUE TITLE
exa-plugin: repay on refund

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#45]

**Comment by Mateo-Soso** [comment]
For the launch, we are going to automatically repay the user's borrowed amount once we have the money in our collecting account and have received the corresponding message to make a refund. The user will, for now, have to repay the interest manually.
If we see that the accumulated amount is low enough, we will start covering for the interest, repaying it from our pocket and automatically when we repay the borrowed amount.
We need to have this possibility covered in the plug-in development to change the configuration if we decide to cover the interests.

**Comment by Mateo-Soso** [comment]
Cryptomate just confirmed that they can't send the refund money to the users account.
Lets work on the new contract
