### ISSUE TITLE
ui: activity detail info

### ISSUE THREAD

**Issue by Mateo-Soso** [exactly/mobile#80]
Screen where the user can see details of the transaction:
For purchases:
amount
date
merchant
type (in-store or online)
debit or credit
Installments
tx hash 

For repayments
date
amount
token used to repay
tx hash
link to statement

For add funds movements
date
amount
token
from
tx hash

For withdraws
date
amount
token
to
tx hash

**Comment by cruzdanilo** [comment]
related to #115
