### ISSUE TITLE
app: integrate lifi (new cross-repay)

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/mobile#96]
li.fi

**Comment by Mateo-Soso** [comment]
We should do it inside an investment screen, where users in the future can also get Exa and RWA.
Charge a fee on top of the socket fees and make sure that we limit the assets our users can get.

**Comment by Mateo-Soso** [comment]
Li fi docs for widget https://li.fi/knowledge-hub/li-fi-widget/ 
They allow swap fees.
Personalized whitelisting of assets only with API integration.
